const NODES_FETCH_DATA_SUCCESS = 'NODES_FETCH_DATA_SUCCESS';
const TOGGLE_VIEW_MODE = 'TOGGLE_VIEW_MODE';
const DISPLAY_NODE_INFO = 'DISPLAY_NODE_INFO,';
const HIDE_NODE_INFO = 'HIDE_NODE_INFO';
const UPDATE_CURRENT_NODE = 'UPDATE_CURRENT_NODE';
const SERVICES_FETCH = 'SERVICES_FETCH';
const TOGGLE_SERVICE_TYPE = 'TOGGLE_SERVICE_TYPE';
const TOGGLE_SERVICE = 'TOGGLE_SERVICE';
const UPDATE_CURRENT_SERVICE = 'UPDATE_CURRENT_SERVICE';
const PODS_FETCH = 'PODS_FETCH';
const DISPLAY_POD_INFO = 'DISPLAY_POD_INFO';
const HIDE_POD_INFO = 'HIDE_POD_INFO';
const DISPLAY_SERVICE_INFO = 'DISPLAY_SERVICE_INFO';
const HIDE_SERVICE_INFO = 'HIDE_SERVICE_INFO';
const UPDATE_CURRENT_POD = 'UPDATE_CURRENT_POD';
const PVS_FETCH = 'PVS_FETCH';
const UPDATE_CURRENT_PV = 'UPDATE_CURRENT_PV';
const DISPLAY_PV_INFO = 'DISPLAY_PV_INFO';
const HIDE_PV_INFO = 'HIDE_PV_INFO';

export {
  NODES_FETCH_DATA_SUCCESS,
  TOGGLE_VIEW_MODE,
  DISPLAY_NODE_INFO,
  HIDE_NODE_INFO,
  UPDATE_CURRENT_NODE,
  SERVICES_FETCH,
  TOGGLE_SERVICE_TYPE,
  TOGGLE_SERVICE,
  PODS_FETCH,
  DISPLAY_SERVICE_INFO,
  HIDE_SERVICE_INFO,
  UPDATE_CURRENT_SERVICE,
  UPDATE_CURRENT_POD,
  DISPLAY_POD_INFO,
  HIDE_POD_INFO,
  PVS_FETCH,
  UPDATE_CURRENT_PV,
  DISPLAY_PV_INFO,
  HIDE_PV_INFO
};
