const NODES_FETCH_DATA_SUCCESS = 'NODES_FETCH_DATA_SUCCESS';
const DISPLAY_NODE_INFO = 'DISPLAY_NODE_INFO';
const HIDE_NODE_INFO = 'HIDE_NODE_INFO';
const SERVICES_FETCH = 'bananas';
const PODS_FETCH = 'apples';

export {
    NODES_FETCH_DATA_SUCCESS,
    DISPLAY_NODE_INFO,
    HIDE_NODE_INFO,
    SERVICES_FETCH,
    PODS_FETCH
};